# docker run -it --cpu-shares=100 --rm -v `pwd`/chat.js:/var/www/unsee/chat.js -v `pwd`/../ssl_certs/unsee.cc.crt:/etc/ssl/certs/unsee.cc.crt -v `pwd`/../ssl_certs/unsee.cc.key:/etc/ssl/private/unsee.cc.key -p 3000:3000 api
chat:
  build: .
  ports:
    - 3000:3000
  net: "host"
  volumes:
    - ./chat.js:/var/www/unsee/chat.js
    - /etc/ssl/certs/unsee.cc.crt:/etc/ssl/certs/unsee.cc.crt
    - /etc/ssl/private/unsee.cc.key:/etc/ssl/private/unsee.cc.key
